[workspace]
members = [
    "crm",
]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.82"
prost = "0.12.4"
prost-build = "0.12.4"
prost-types = "0.12.4"
tonic = { version = "0.11.0", features = ["zstd"] }
tonic-build = "0.11.0"
